### ISSUE TITLE
Question relating the amount of output mixture parameters

### ISSUE THREAD

**Issue by vanmil** [cpmpercussion/keras-mdn-layer#14]
Hi! Thanks for your implementation, great work. I am still learning about mixture density networks and have a question relating to the amount of output parameters. 

In this implementation it seems that there are `(2 * NUMBER_MIXTURES * OUTPUT_DIM) + (NUMBER_MIXTURES)` parameters. For example, in the Kanji notebook this results in `2*10*3 + 10 = 70` outputs. 

However, in some other implementations of MDN-RNN's such as the one from World Models (https://github.com/hardmaru/WorldModelsExperiments/blob/master/carracing/rnn/rnn.py) there seems to be `3 * NUMBER_MIXTURES * OUTPUT_DIM` output parameters. I think the difference is that you only model NUMBER_MIXTURES mixing coefficients, and they model NUM_MIXTURES * OUTPUT_DIM mixture coefficients. In your Kanji notebook this would result in `3*10*3 = 90` outputs.

I was wondering why this difference between implementations exists? Is this due to the difference that your code does not model the covariance of the Gaussians or is that something unrelated? Thanks in advance!

**Comment by cpmpercussion** [comment]
Astute observation! I've noticed this as well.

Yep, MDNs can be different depending on how you want to set up the mixture model at the output. This library is a bit different from hardmaru's one over in the World Models repo. But I don't think it's to do with covariances.

For this library, the output model is a mixture of multivariate Gaussian distributions. Each of the Gaussian distributions has a dimension (`OUTPUT_DIM`), and is constrained to have a diagonal covariance matrix (this just makes it easy to calculate the PDF, and so that we can use the TensorFlow `MultivariateNormalDiag` implementation of this distribution). This means that there are two parameters for each dimension of the Gaussian distributions, a centre and a variance, which could be called `mu` and `sigma`. This gives us `2 * OUTPUT_DIM` parameters for each multivariate Gaussian distribution.

Now, of course, we need to have one independent instance of this distribution for each component of the mixture model. So this gives us `NUMBER_MIXTURES * 2 * OUTPUT_DIM` parameters for all of the Gaussian distributions.

There's one last thing: the parameters that mix these Gaussian components such that some of them are more or less likely to be drawn than others. For this, we need one parameter for each mixture component (`pi`).
 
Thus, we end up with a total of `(NUMBER_MIXTURES * 2 * OUTPUT_DIM) + NUMBER_MIXTURES` parameters.

---

Now as far as I can tell, and it has been a while (9-10 months) since I checked, but the World Models repo actually uses a completely separate mixture distribution for each dimension to be modelled.

So this gives us `NUM_MIXTURES * (2 + 1) == NUM_MIXTURES * 3` for each dimension, and then `NUM_MIXTURES * 3 * OUTPUT_DIM` for the complete model.

This method for constructing the output distribution didn't (and still doesn't) make as much sense to me because the mixtures are kind of independent for each dimension. I think the samples must then be drawn independently for each dimension. 

My view is that each mixture should be a complete model of the "World" (or data), that is all dimensions at once. And that you can navigate between "Worlds" by manipulating the mixing variables.

I asked hardmaru about this at Neurips and he said (very politely) something along the lines of "because it trains better"---tbh I can't argue with that! If it works, then great! I still think that my version here has the benefit of each mixture component modelling all output dimensions at once, but it is certainly a bit more complicated for training (due to the `MultivariateNormalDiag` distribution). Additionally, some of my colleagues have tried replicating some of the World Models tasks (e.g., vizdoom dodging) and the results may not have been quite as good (not sure of details).

Certainly happy to continue thinking about the best way to model multidimensional data here! Any thoughts or experiments are welcome!
